[build]
  command = "npm run build && npx prisma generate && node prisma/seed.js"
  functions = "functions"
[dev]
  publish = "dist"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"