[build]
  functions = "functions"
  command = "CI=false npx prisma generate && node functions/prisma/seed.js"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"